### PR TITLE
add grafana/pyroscope

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
Towards https://github.com/giantswarm/giantswarm/issues/29151

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuantumEnigmaa** [comment]
The job for pushing the image to docker.io keep failing :/

**Comment by QuantumEnigmaa** [comment]
@giantswarm/team-honeybadger Even though the job succeeded, there still isn't any image in the docker.io registry : https://hub.docker.com/r/giantswarm/pyroscope/tags

Is there a way to force push it there ?

**Comment by QuentinBisson** [comment]
We're trying to move away from docker using the new goci registry. As long as the image IS there then we're fine

**Comment by QuentinBisson** [comment]
docker pull should suffixe with the correct registry. Images are public

**Comment by QuantumEnigmaa** [comment]
Do you have the base url for the registry ? I don't know goci and I can't find it in retagger :/

**Comment by QuentinBisson** [comment]
Sorry not really. You Can check pmo or object storage operator values. Marian did the change

**Comment by QuantumEnigmaa** [comment]
Ok I checked and the image is present on the `gsoci` registry :)

**Pull request merged**
