### PR TITLE
Add image for Helm chart testing

### PR DESCRIPTION
**Pull request by yasn77**
Needed for https://github.com/giantswarm/architect-orb/pull/65

_Retagger_

https://github.com/giantswarm/giantswarm/blob/master/ops-recipes/container-registry.md

---

### CODE REVIEW

**Comment by yasn77** [comment]
Quay Repo created -> https://quay.io/repository/giantswarm/helm-chart-testing

**Comment by yasn77** [comment]
Repo created in China -> https://cr.console.aliyun.com/repository/cn-shanghai/giantswarm/helm-chart-testing/details

**Comment by MarcelMue** [comment]
You don't need to create the repos manually - retagger will take care :)

**Comment by yasn77** [comment]
> You don't need to create the repos manually - retagger will take care :)

Ah, didn't know that. It's the first time I am adding a new image :)

Thanks

**Pull request merged**
