### PR TITLE
adds hugo and nginx

### PR DESCRIPTION
**Pull request by puja108**
needed for secure hugo deployment of internal docs

quay and aliyun repos created

### CODE REVIEW

**Comment by puja108** [comment]
there was a strange version of oauth2 proxy already retagged, but I want the official upstream one, I guess as long as my tags don't overlap this should work, right?

**Comment by puja108** [comment]
not sure why the image test is failing, what does that thing do?

**Comment by MarcelMue** [comment]
`images are not sorted alphabetically` - a little hidden in the error message.

**Comment by puja108** [comment]
oh, I have to sort it... now that is something that was not in docs

**Pull request merged**
